name: Lint workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  OPENSEARCH_DASHBOARDS_VERSION: '2.2'
jobs:
  tests:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenSearch Dashboards
        uses: actions/checkout@v2
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          ref: ${{ env.OPENSEARCH_DASHBOARDS_VERSION }}
          path: OpenSearch-Dashboards
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './OpenSearch-Dashboards/.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Yarn
        # Need to use bash to avoid having a windows/linux specific step
        shell: bash
        run: |
          YARN_VERSION=$(node -p "require('./OpenSearch-Dashboards/package.json').engines.yarn")
          echo "Installing yarn@$YARN_VERSION"
          npm i -g yarn@$YARN_VERSION
      - run: node -v
      - run: yarn -v
      - name: Checkout ML Commons OpenSearch Dashboards plugin
        uses: actions/checkout@v2
        with:
          path: OpenSearch-Dashboards/plugins/ml-commons-dashboards
      - name: Bootstrap plugin/opensearch-dashboards
        run: |
          cd OpenSearch-Dashboards/plugins/ml-commons-dashboards
          yarn osd bootstrap
      - name: Run lint
        run: |
          cd OpenSearch-Dashboards/plugins/ml-commons-dashboards
          yarn run lint:es --ext .tsx --ext .ts .
